
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'FeatureExample': typeof import("../components/content/advertisements/FeatureExample.vue")['default']
    'SponsorExample': typeof import("../components/content/advertisements/SponsorExample.vue")['default']
    'BlogGrid': typeof import("../components/content/blog/BlogGrid.vue")['default']
    'DirectoryGrid': typeof import("../components/content/directory/DirectoryGrid.vue")['default']
    'Search': typeof import("../components/content/directory/Search.vue")['default']
    'LinkButton': typeof import("../components/content/general/LinkButton.vue")['default']
    'NewsletterForm': typeof import("../components/content/general/NewsletterForm.vue")['default']
    'NewsletterWithCTA': typeof import("../components/content/general/NewsletterWithCTA.vue")['default']
    'Tweet': typeof import("../components/content/general/Tweet.vue")['default']
    'CenterHero': typeof import("../components/content/hero/CenterHero.vue")['default']
    'ImageHero': typeof import("../components/content/hero/ImageHero.vue")['default']
    'SimpleLeftHero': typeof import("../components/content/hero/SimpleLeftHero.vue")['default']
    'TwoColumnHero': typeof import("../components/content/hero/TwoColumnHero.vue")['default']
    'About': typeof import("../components/content/pages/About.vue")['default']
    'BlogPost': typeof import("../components/content/pages/BlogPost.vue")['default']
    'Blogs': typeof import("../components/content/pages/Blogs.vue")['default']
    'Changelog': typeof import("../components/content/pages/Changelog.vue")['default']
    'Contact': typeof import("../components/content/pages/Contact.vue")['default']
    'Customer': typeof import("../components/content/pages/Customer.vue")['default']
    'Customers': typeof import("../components/content/pages/Customers.vue")['default']
    'Help': typeof import("../components/content/pages/Help.vue")['default']
    'Home': typeof import("../components/content/pages/Home.vue")['default']
    'Integrations': typeof import("../components/content/pages/Integrations.vue")['default']
    'IntegrationsSingle': typeof import("../components/content/pages/IntegrationsSingle.vue")['default']
    'Pricing': typeof import("../components/content/pages/Pricing.vue")['default']
    'ResetPassword': typeof import("../components/content/pages/ResetPassword.vue")['default']
    'SignIn': typeof import("../components/content/pages/SignIn.vue")['default']
    'SignUp': typeof import("../components/content/pages/SignUp.vue")['default']
    'BlogList': typeof import("../components/content/partials/BlogList.vue")['default']
    'BlogSingle': typeof import("../components/content/partials/BlogSingle.vue")['default']
    'Clients': typeof import("../components/content/partials/Clients.vue")['default']
    'Cta': typeof import("../components/content/partials/Cta.vue")['default']
    'Cta02': typeof import("../components/content/partials/Cta02.vue")['default']
    'Cta03': typeof import("../components/content/partials/Cta03.vue")['default']
    'Cta04': typeof import("../components/content/partials/Cta04.vue")['default']
    'Cta05': typeof import("../components/content/partials/Cta05.vue")['default']
    'CustomersList': typeof import("../components/content/partials/CustomersList.vue")['default']
    'CustomersRelated': typeof import("../components/content/partials/CustomersRelated.vue")['default']
    'Faqs': typeof import("../components/content/partials/Faqs.vue")['default']
    'Features': typeof import("../components/content/partials/Features.vue")['default']
    'Features02': typeof import("../components/content/partials/Features02.vue")['default']
    'Features03': typeof import("../components/content/partials/Features03.vue")['default']
    'Features04': typeof import("../components/content/partials/Features04.vue")['default']
    'Features05': typeof import("../components/content/partials/Features05.vue")['default']
    'Footer': typeof import("../components/content/partials/Footer.vue")['default']
    'Header': typeof import("../components/content/partials/Header.vue")['default']
    'Hero': typeof import("../components/content/partials/Hero.vue")['default']
    'HeroAbout': typeof import("../components/content/partials/HeroAbout.vue")['default']
    'Highlighter': typeof import("../components/content/partials/Highlighter.vue")['default']
    'HighlighterItem': typeof import("../components/content/partials/HighlighterItem.vue")['default']
    'HighlighterItem02': typeof import("../components/content/partials/HighlighterItem02.vue")['default']
    'IntegrationCard': typeof import("../components/content/partials/IntegrationCard.vue")['default']
    'IntegrationsCarousel': typeof import("../components/content/partials/IntegrationsCarousel.vue")['default']
    'IntegrationsHero': typeof import("../components/content/partials/IntegrationsHero.vue")['default']
    'IntegrationsList': typeof import("../components/content/partials/IntegrationsList.vue")['default']
    'PageIllustration': typeof import("../components/content/partials/PageIllustration.vue")['default']
    'Particles': typeof import("../components/content/partials/Particles.vue")['default']
    'PricingHero': typeof import("../components/content/partials/PricingHero.vue")['default']
    'PricingHome': typeof import("../components/content/partials/PricingHome.vue")['default']
    'PricingTable': typeof import("../components/content/partials/PricingTable.vue")['default']
    'Recruitment': typeof import("../components/content/partials/Recruitment.vue")['default']
    'Story': typeof import("../components/content/partials/Story.vue")['default']
    'Team': typeof import("../components/content/partials/Team.vue")['default']
    'Testimonials': typeof import("../components/content/partials/Testimonials.vue")['default']
    'Testimonials02': typeof import("../components/content/partials/Testimonials02.vue")['default']
    'TestimonialsCarousel': typeof import("../components/content/partials/TestimonialsCarousel.vue")['default']
    'ProseA': typeof import("../components/content/prose/ProseA.vue")['default']
    'TallyForm': typeof import("../components/content/submit/TallyForm.vue")['default']
    'MousePosition': typeof import("../components/content/utils/MousePosition")['default']
    'AppFooter': typeof import("../components/app/Footer.vue")['default']
    'AppLayout': typeof import("../components/app/Layout.vue")['default']
    'AppLogo': typeof import("../components/app/Logo.vue")['default']
    'AppNavbar': typeof import("../components/app/Navbar.vue")['default']
    'AppHeaderBanner': typeof import("../components/app/header/Banner.vue")['default']
    'AppHeaderColorSelector': typeof import("../components/app/header/ColorSelector.vue")['default']
    'AppHeaderDot': typeof import("../components/app/header/Dot.vue")['default']
    'DirectoryEmptyQueryIndicator': typeof import("../components/directory/EmptyQueryIndicator.vue")['default']
    'DirectoryFeaturedRecommendation': typeof import("../components/directory/Featured/Recommendation.vue")['default']
    'DirectoryFeaturedTag': typeof import("../components/directory/Featured/Tag.vue")['default']
    'DirectoryItem': typeof import("../components/directory/Item.vue")['default']
    'DirectoryPureGrid': typeof import("../components/directory/PureGrid.vue")['default']
    'DirectorySubmitBox': typeof import("../components/directory/SubmitBox.vue")['default']
    'DocumentEmpty': typeof import("../components/document/Empty.vue")['default']
    'DocumentNotFound': typeof import("../components/document/NotFound.vue")['default']
    'DocumentProse': typeof import("../components/document/Prose.vue")['default']
    'UiButton': typeof import("../components/ui/Button.vue")['default']
    'UiCard': typeof import("../components/ui/Card.vue")['default']
    'UiShadowCard': typeof import("../components/ui/ShadowCard.vue")['default']
    'UiTag': typeof import("../components/ui/Tag.vue")['default']
    'UiTagGrid': typeof import("../components/ui/tag/Grid.vue")['default']
    'UiTagSelect': typeof import("../components/ui/tag/Select.vue")['default']
    'ContentDoc': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']
    'ContentList': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']
    'ContentNavigation': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']
    'ContentQuery': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']
    'ContentRenderer': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
    'ContentRendererMarkdown': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']
    'ContentSlot': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']
    'DocumentDrivenEmpty': typeof import("../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue")['default']
    'DocumentDrivenNotFound': typeof import("../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue")['default']
    'Markdown': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']
    'ProseCode': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue")['default']
    'ProseCodeInline': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default']
    'ProsePre': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue")['default']
    'ProseBlockquote': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
    'ProseEm': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
    'ProseH1': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
    'ProseH2': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
    'ProseH3': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
    'ProseH4': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
    'ProseH5': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
    'ProseH6': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
    'ProseHr': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
    'ProseImg': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
    'ProseLi': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
    'ProseOl': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
    'ProseP': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
    'ProseScript': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
    'ProseStrong': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
    'ProseTable': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
    'ProseTbody': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
    'ProseTd': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
    'ProseTh': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
    'ProseThead': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
    'ProseTr': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
    'ProseUl': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
    'ContentPreviewMode': typeof import("../node_modules/@nuxthq/studio/dist/runtime/components/ContentPreviewMode.vue")['default']
    'ScriptCarbonAds': typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCarbonAds.vue")['default']
    'ScriptCrisp': typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCrisp.vue")['default']
    'ScriptGoogleAdsense': typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleAdsense.vue")['default']
    'ScriptGoogleMaps': typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleMaps.vue")['default']
    'ScriptIntercom': typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptIntercom.vue")['default']
    'ScriptLemonSqueezy': typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLemonSqueezy.vue")['default']
    'ScriptLoadingIndicator': typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLoadingIndicator.vue")['default']
    'ScriptStripePricingTable': typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptStripePricingTable.vue")['default']
    'ScriptVimeoPlayer': typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptVimeoPlayer.vue")['default']
    'ScriptYouTubePlayer': typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptYouTubePlayer.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'MDC': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
    'MDCRenderer': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
    'MDCSlot': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
    'Icon': typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'ColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'SiteLink': typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
    'RobotMeta': typeof import("../node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
    'OgImage': typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImage")['default']
    'OgImageScreenshot': typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImageScreenshot")['default']
    'SchemaOrgDebug': typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
    'SchemaOrgArticle': typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
    'SchemaOrgBreadcrumb': typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
    'SchemaOrgComment': typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
    'SchemaOrgEvent': typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
    'SchemaOrgFoodEstablishment': typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
    'SchemaOrgHowTo': typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
    'SchemaOrgImage': typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
    'SchemaOrgJobPosting': typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
    'SchemaOrgLocalBusiness': typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
    'SchemaOrgOrganization': typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
    'SchemaOrgPerson': typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
    'SchemaOrgProduct': typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
    'SchemaOrgQuestion': typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
    'SchemaOrgRecipe': typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
    'SchemaOrgReview': typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
    'SchemaOrgVideo': typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
    'SchemaOrgWebPage': typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
    'SchemaOrgWebSite': typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
    'SchemaOrgMovie': typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
    'SchemaOrgCourse': typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
    'SchemaOrgItemList': typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
    'SchemaOrgBook': typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
    'SchemaOrgSoftwareApp': typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyFeatureExample': typeof import("../components/content/advertisements/FeatureExample.vue")['default']
    'LazySponsorExample': typeof import("../components/content/advertisements/SponsorExample.vue")['default']
    'LazyBlogGrid': typeof import("../components/content/blog/BlogGrid.vue")['default']
    'LazyDirectoryGrid': typeof import("../components/content/directory/DirectoryGrid.vue")['default']
    'LazySearch': typeof import("../components/content/directory/Search.vue")['default']
    'LazyLinkButton': typeof import("../components/content/general/LinkButton.vue")['default']
    'LazyNewsletterForm': typeof import("../components/content/general/NewsletterForm.vue")['default']
    'LazyNewsletterWithCTA': typeof import("../components/content/general/NewsletterWithCTA.vue")['default']
    'LazyTweet': typeof import("../components/content/general/Tweet.vue")['default']
    'LazyCenterHero': typeof import("../components/content/hero/CenterHero.vue")['default']
    'LazyImageHero': typeof import("../components/content/hero/ImageHero.vue")['default']
    'LazySimpleLeftHero': typeof import("../components/content/hero/SimpleLeftHero.vue")['default']
    'LazyTwoColumnHero': typeof import("../components/content/hero/TwoColumnHero.vue")['default']
    'LazyAbout': typeof import("../components/content/pages/About.vue")['default']
    'LazyBlogPost': typeof import("../components/content/pages/BlogPost.vue")['default']
    'LazyBlogs': typeof import("../components/content/pages/Blogs.vue")['default']
    'LazyChangelog': typeof import("../components/content/pages/Changelog.vue")['default']
    'LazyContact': typeof import("../components/content/pages/Contact.vue")['default']
    'LazyCustomer': typeof import("../components/content/pages/Customer.vue")['default']
    'LazyCustomers': typeof import("../components/content/pages/Customers.vue")['default']
    'LazyHelp': typeof import("../components/content/pages/Help.vue")['default']
    'LazyHome': typeof import("../components/content/pages/Home.vue")['default']
    'LazyIntegrations': typeof import("../components/content/pages/Integrations.vue")['default']
    'LazyIntegrationsSingle': typeof import("../components/content/pages/IntegrationsSingle.vue")['default']
    'LazyPricing': typeof import("../components/content/pages/Pricing.vue")['default']
    'LazyResetPassword': typeof import("../components/content/pages/ResetPassword.vue")['default']
    'LazySignIn': typeof import("../components/content/pages/SignIn.vue")['default']
    'LazySignUp': typeof import("../components/content/pages/SignUp.vue")['default']
    'LazyBlogList': typeof import("../components/content/partials/BlogList.vue")['default']
    'LazyBlogSingle': typeof import("../components/content/partials/BlogSingle.vue")['default']
    'LazyClients': typeof import("../components/content/partials/Clients.vue")['default']
    'LazyCta': typeof import("../components/content/partials/Cta.vue")['default']
    'LazyCta02': typeof import("../components/content/partials/Cta02.vue")['default']
    'LazyCta03': typeof import("../components/content/partials/Cta03.vue")['default']
    'LazyCta04': typeof import("../components/content/partials/Cta04.vue")['default']
    'LazyCta05': typeof import("../components/content/partials/Cta05.vue")['default']
    'LazyCustomersList': typeof import("../components/content/partials/CustomersList.vue")['default']
    'LazyCustomersRelated': typeof import("../components/content/partials/CustomersRelated.vue")['default']
    'LazyFaqs': typeof import("../components/content/partials/Faqs.vue")['default']
    'LazyFeatures': typeof import("../components/content/partials/Features.vue")['default']
    'LazyFeatures02': typeof import("../components/content/partials/Features02.vue")['default']
    'LazyFeatures03': typeof import("../components/content/partials/Features03.vue")['default']
    'LazyFeatures04': typeof import("../components/content/partials/Features04.vue")['default']
    'LazyFeatures05': typeof import("../components/content/partials/Features05.vue")['default']
    'LazyFooter': typeof import("../components/content/partials/Footer.vue")['default']
    'LazyHeader': typeof import("../components/content/partials/Header.vue")['default']
    'LazyHero': typeof import("../components/content/partials/Hero.vue")['default']
    'LazyHeroAbout': typeof import("../components/content/partials/HeroAbout.vue")['default']
    'LazyHighlighter': typeof import("../components/content/partials/Highlighter.vue")['default']
    'LazyHighlighterItem': typeof import("../components/content/partials/HighlighterItem.vue")['default']
    'LazyHighlighterItem02': typeof import("../components/content/partials/HighlighterItem02.vue")['default']
    'LazyIntegrationCard': typeof import("../components/content/partials/IntegrationCard.vue")['default']
    'LazyIntegrationsCarousel': typeof import("../components/content/partials/IntegrationsCarousel.vue")['default']
    'LazyIntegrationsHero': typeof import("../components/content/partials/IntegrationsHero.vue")['default']
    'LazyIntegrationsList': typeof import("../components/content/partials/IntegrationsList.vue")['default']
    'LazyPageIllustration': typeof import("../components/content/partials/PageIllustration.vue")['default']
    'LazyParticles': typeof import("../components/content/partials/Particles.vue")['default']
    'LazyPricingHero': typeof import("../components/content/partials/PricingHero.vue")['default']
    'LazyPricingHome': typeof import("../components/content/partials/PricingHome.vue")['default']
    'LazyPricingTable': typeof import("../components/content/partials/PricingTable.vue")['default']
    'LazyRecruitment': typeof import("../components/content/partials/Recruitment.vue")['default']
    'LazyStory': typeof import("../components/content/partials/Story.vue")['default']
    'LazyTeam': typeof import("../components/content/partials/Team.vue")['default']
    'LazyTestimonials': typeof import("../components/content/partials/Testimonials.vue")['default']
    'LazyTestimonials02': typeof import("../components/content/partials/Testimonials02.vue")['default']
    'LazyTestimonialsCarousel': typeof import("../components/content/partials/TestimonialsCarousel.vue")['default']
    'LazyProseA': typeof import("../components/content/prose/ProseA.vue")['default']
    'LazyTallyForm': typeof import("../components/content/submit/TallyForm.vue")['default']
    'LazyMousePosition': typeof import("../components/content/utils/MousePosition")['default']
    'LazyAppFooter': typeof import("../components/app/Footer.vue")['default']
    'LazyAppLayout': typeof import("../components/app/Layout.vue")['default']
    'LazyAppLogo': typeof import("../components/app/Logo.vue")['default']
    'LazyAppNavbar': typeof import("../components/app/Navbar.vue")['default']
    'LazyAppHeaderBanner': typeof import("../components/app/header/Banner.vue")['default']
    'LazyAppHeaderColorSelector': typeof import("../components/app/header/ColorSelector.vue")['default']
    'LazyAppHeaderDot': typeof import("../components/app/header/Dot.vue")['default']
    'LazyDirectoryEmptyQueryIndicator': typeof import("../components/directory/EmptyQueryIndicator.vue")['default']
    'LazyDirectoryFeaturedRecommendation': typeof import("../components/directory/Featured/Recommendation.vue")['default']
    'LazyDirectoryFeaturedTag': typeof import("../components/directory/Featured/Tag.vue")['default']
    'LazyDirectoryItem': typeof import("../components/directory/Item.vue")['default']
    'LazyDirectoryPureGrid': typeof import("../components/directory/PureGrid.vue")['default']
    'LazyDirectorySubmitBox': typeof import("../components/directory/SubmitBox.vue")['default']
    'LazyDocumentEmpty': typeof import("../components/document/Empty.vue")['default']
    'LazyDocumentNotFound': typeof import("../components/document/NotFound.vue")['default']
    'LazyDocumentProse': typeof import("../components/document/Prose.vue")['default']
    'LazyUiButton': typeof import("../components/ui/Button.vue")['default']
    'LazyUiCard': typeof import("../components/ui/Card.vue")['default']
    'LazyUiShadowCard': typeof import("../components/ui/ShadowCard.vue")['default']
    'LazyUiTag': typeof import("../components/ui/Tag.vue")['default']
    'LazyUiTagGrid': typeof import("../components/ui/tag/Grid.vue")['default']
    'LazyUiTagSelect': typeof import("../components/ui/tag/Select.vue")['default']
    'LazyContentDoc': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']
    'LazyContentList': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']
    'LazyContentNavigation': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']
    'LazyContentQuery': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']
    'LazyContentRenderer': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
    'LazyContentRendererMarkdown': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']
    'LazyContentSlot': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']
    'LazyDocumentDrivenEmpty': typeof import("../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue")['default']
    'LazyDocumentDrivenNotFound': typeof import("../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue")['default']
    'LazyMarkdown': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']
    'LazyProseCode': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue")['default']
    'LazyProseCodeInline': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default']
    'LazyProsePre': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue")['default']
    'LazyProseBlockquote': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
    'LazyProseEm': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
    'LazyProseH1': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
    'LazyProseH2': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
    'LazyProseH3': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
    'LazyProseH4': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
    'LazyProseH5': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
    'LazyProseH6': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
    'LazyProseHr': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
    'LazyProseImg': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
    'LazyProseLi': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
    'LazyProseOl': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
    'LazyProseP': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
    'LazyProseScript': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
    'LazyProseStrong': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
    'LazyProseTable': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
    'LazyProseTbody': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
    'LazyProseTd': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
    'LazyProseTh': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
    'LazyProseThead': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
    'LazyProseTr': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
    'LazyProseUl': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
    'LazyContentPreviewMode': typeof import("../node_modules/@nuxthq/studio/dist/runtime/components/ContentPreviewMode.vue")['default']
    'LazyScriptCarbonAds': typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCarbonAds.vue")['default']
    'LazyScriptCrisp': typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCrisp.vue")['default']
    'LazyScriptGoogleAdsense': typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleAdsense.vue")['default']
    'LazyScriptGoogleMaps': typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleMaps.vue")['default']
    'LazyScriptIntercom': typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptIntercom.vue")['default']
    'LazyScriptLemonSqueezy': typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLemonSqueezy.vue")['default']
    'LazyScriptLoadingIndicator': typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLoadingIndicator.vue")['default']
    'LazyScriptStripePricingTable': typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptStripePricingTable.vue")['default']
    'LazyScriptVimeoPlayer': typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptVimeoPlayer.vue")['default']
    'LazyScriptYouTubePlayer': typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptYouTubePlayer.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'LazyMDC': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
    'LazyMDCRenderer': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
    'LazyMDCSlot': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
    'LazyIcon': typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'LazyColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazySiteLink': typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
    'LazyRobotMeta': typeof import("../node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
    'LazyOgImage': typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImage")['default']
    'LazyOgImageScreenshot': typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImageScreenshot")['default']
    'LazySchemaOrgDebug': typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
    'LazySchemaOrgArticle': typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
    'LazySchemaOrgBreadcrumb': typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
    'LazySchemaOrgComment': typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
    'LazySchemaOrgEvent': typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
    'LazySchemaOrgFoodEstablishment': typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
    'LazySchemaOrgHowTo': typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
    'LazySchemaOrgImage': typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
    'LazySchemaOrgJobPosting': typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
    'LazySchemaOrgLocalBusiness': typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
    'LazySchemaOrgOrganization': typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
    'LazySchemaOrgPerson': typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
    'LazySchemaOrgProduct': typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
    'LazySchemaOrgQuestion': typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
    'LazySchemaOrgRecipe': typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
    'LazySchemaOrgReview': typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
    'LazySchemaOrgVideo': typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
    'LazySchemaOrgWebPage': typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
    'LazySchemaOrgWebSite': typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
    'LazySchemaOrgMovie': typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
    'LazySchemaOrgCourse': typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
    'LazySchemaOrgItemList': typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
    'LazySchemaOrgBook': typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
    'LazySchemaOrgSoftwareApp': typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const FeatureExample: typeof import("../components/content/advertisements/FeatureExample.vue")['default']
export const SponsorExample: typeof import("../components/content/advertisements/SponsorExample.vue")['default']
export const BlogGrid: typeof import("../components/content/blog/BlogGrid.vue")['default']
export const DirectoryGrid: typeof import("../components/content/directory/DirectoryGrid.vue")['default']
export const Search: typeof import("../components/content/directory/Search.vue")['default']
export const LinkButton: typeof import("../components/content/general/LinkButton.vue")['default']
export const NewsletterForm: typeof import("../components/content/general/NewsletterForm.vue")['default']
export const NewsletterWithCTA: typeof import("../components/content/general/NewsletterWithCTA.vue")['default']
export const Tweet: typeof import("../components/content/general/Tweet.vue")['default']
export const CenterHero: typeof import("../components/content/hero/CenterHero.vue")['default']
export const ImageHero: typeof import("../components/content/hero/ImageHero.vue")['default']
export const SimpleLeftHero: typeof import("../components/content/hero/SimpleLeftHero.vue")['default']
export const TwoColumnHero: typeof import("../components/content/hero/TwoColumnHero.vue")['default']
export const About: typeof import("../components/content/pages/About.vue")['default']
export const BlogPost: typeof import("../components/content/pages/BlogPost.vue")['default']
export const Blogs: typeof import("../components/content/pages/Blogs.vue")['default']
export const Changelog: typeof import("../components/content/pages/Changelog.vue")['default']
export const Contact: typeof import("../components/content/pages/Contact.vue")['default']
export const Customer: typeof import("../components/content/pages/Customer.vue")['default']
export const Customers: typeof import("../components/content/pages/Customers.vue")['default']
export const Help: typeof import("../components/content/pages/Help.vue")['default']
export const Home: typeof import("../components/content/pages/Home.vue")['default']
export const Integrations: typeof import("../components/content/pages/Integrations.vue")['default']
export const IntegrationsSingle: typeof import("../components/content/pages/IntegrationsSingle.vue")['default']
export const Pricing: typeof import("../components/content/pages/Pricing.vue")['default']
export const ResetPassword: typeof import("../components/content/pages/ResetPassword.vue")['default']
export const SignIn: typeof import("../components/content/pages/SignIn.vue")['default']
export const SignUp: typeof import("../components/content/pages/SignUp.vue")['default']
export const BlogList: typeof import("../components/content/partials/BlogList.vue")['default']
export const BlogSingle: typeof import("../components/content/partials/BlogSingle.vue")['default']
export const Clients: typeof import("../components/content/partials/Clients.vue")['default']
export const Cta: typeof import("../components/content/partials/Cta.vue")['default']
export const Cta02: typeof import("../components/content/partials/Cta02.vue")['default']
export const Cta03: typeof import("../components/content/partials/Cta03.vue")['default']
export const Cta04: typeof import("../components/content/partials/Cta04.vue")['default']
export const Cta05: typeof import("../components/content/partials/Cta05.vue")['default']
export const CustomersList: typeof import("../components/content/partials/CustomersList.vue")['default']
export const CustomersRelated: typeof import("../components/content/partials/CustomersRelated.vue")['default']
export const Faqs: typeof import("../components/content/partials/Faqs.vue")['default']
export const Features: typeof import("../components/content/partials/Features.vue")['default']
export const Features02: typeof import("../components/content/partials/Features02.vue")['default']
export const Features03: typeof import("../components/content/partials/Features03.vue")['default']
export const Features04: typeof import("../components/content/partials/Features04.vue")['default']
export const Features05: typeof import("../components/content/partials/Features05.vue")['default']
export const Footer: typeof import("../components/content/partials/Footer.vue")['default']
export const Header: typeof import("../components/content/partials/Header.vue")['default']
export const Hero: typeof import("../components/content/partials/Hero.vue")['default']
export const HeroAbout: typeof import("../components/content/partials/HeroAbout.vue")['default']
export const Highlighter: typeof import("../components/content/partials/Highlighter.vue")['default']
export const HighlighterItem: typeof import("../components/content/partials/HighlighterItem.vue")['default']
export const HighlighterItem02: typeof import("../components/content/partials/HighlighterItem02.vue")['default']
export const IntegrationCard: typeof import("../components/content/partials/IntegrationCard.vue")['default']
export const IntegrationsCarousel: typeof import("../components/content/partials/IntegrationsCarousel.vue")['default']
export const IntegrationsHero: typeof import("../components/content/partials/IntegrationsHero.vue")['default']
export const IntegrationsList: typeof import("../components/content/partials/IntegrationsList.vue")['default']
export const PageIllustration: typeof import("../components/content/partials/PageIllustration.vue")['default']
export const Particles: typeof import("../components/content/partials/Particles.vue")['default']
export const PricingHero: typeof import("../components/content/partials/PricingHero.vue")['default']
export const PricingHome: typeof import("../components/content/partials/PricingHome.vue")['default']
export const PricingTable: typeof import("../components/content/partials/PricingTable.vue")['default']
export const Recruitment: typeof import("../components/content/partials/Recruitment.vue")['default']
export const Story: typeof import("../components/content/partials/Story.vue")['default']
export const Team: typeof import("../components/content/partials/Team.vue")['default']
export const Testimonials: typeof import("../components/content/partials/Testimonials.vue")['default']
export const Testimonials02: typeof import("../components/content/partials/Testimonials02.vue")['default']
export const TestimonialsCarousel: typeof import("../components/content/partials/TestimonialsCarousel.vue")['default']
export const ProseA: typeof import("../components/content/prose/ProseA.vue")['default']
export const TallyForm: typeof import("../components/content/submit/TallyForm.vue")['default']
export const MousePosition: typeof import("../components/content/utils/MousePosition")['default']
export const AppFooter: typeof import("../components/app/Footer.vue")['default']
export const AppLayout: typeof import("../components/app/Layout.vue")['default']
export const AppLogo: typeof import("../components/app/Logo.vue")['default']
export const AppNavbar: typeof import("../components/app/Navbar.vue")['default']
export const AppHeaderBanner: typeof import("../components/app/header/Banner.vue")['default']
export const AppHeaderColorSelector: typeof import("../components/app/header/ColorSelector.vue")['default']
export const AppHeaderDot: typeof import("../components/app/header/Dot.vue")['default']
export const DirectoryEmptyQueryIndicator: typeof import("../components/directory/EmptyQueryIndicator.vue")['default']
export const DirectoryFeaturedRecommendation: typeof import("../components/directory/Featured/Recommendation.vue")['default']
export const DirectoryFeaturedTag: typeof import("../components/directory/Featured/Tag.vue")['default']
export const DirectoryItem: typeof import("../components/directory/Item.vue")['default']
export const DirectoryPureGrid: typeof import("../components/directory/PureGrid.vue")['default']
export const DirectorySubmitBox: typeof import("../components/directory/SubmitBox.vue")['default']
export const DocumentEmpty: typeof import("../components/document/Empty.vue")['default']
export const DocumentNotFound: typeof import("../components/document/NotFound.vue")['default']
export const DocumentProse: typeof import("../components/document/Prose.vue")['default']
export const UiButton: typeof import("../components/ui/Button.vue")['default']
export const UiCard: typeof import("../components/ui/Card.vue")['default']
export const UiShadowCard: typeof import("../components/ui/ShadowCard.vue")['default']
export const UiTag: typeof import("../components/ui/Tag.vue")['default']
export const UiTagGrid: typeof import("../components/ui/tag/Grid.vue")['default']
export const UiTagSelect: typeof import("../components/ui/tag/Select.vue")['default']
export const ContentDoc: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']
export const ContentList: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']
export const ContentNavigation: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']
export const ContentQuery: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']
export const ContentRenderer: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
export const ContentRendererMarkdown: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']
export const ContentSlot: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']
export const DocumentDrivenEmpty: typeof import("../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue")['default']
export const DocumentDrivenNotFound: typeof import("../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue")['default']
export const Markdown: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']
export const ProseCode: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue")['default']
export const ProseCodeInline: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default']
export const ProsePre: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue")['default']
export const ProseBlockquote: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
export const ProseEm: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
export const ProseH1: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
export const ProseH2: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
export const ProseH3: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
export const ProseH4: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
export const ProseH5: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
export const ProseH6: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
export const ProseHr: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
export const ProseImg: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
export const ProseLi: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
export const ProseOl: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
export const ProseP: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
export const ProseScript: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
export const ProseStrong: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
export const ProseTable: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
export const ProseTbody: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
export const ProseTd: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
export const ProseTh: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
export const ProseThead: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
export const ProseTr: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
export const ProseUl: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
export const ContentPreviewMode: typeof import("../node_modules/@nuxthq/studio/dist/runtime/components/ContentPreviewMode.vue")['default']
export const ScriptCarbonAds: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCarbonAds.vue")['default']
export const ScriptCrisp: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCrisp.vue")['default']
export const ScriptGoogleAdsense: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleAdsense.vue")['default']
export const ScriptGoogleMaps: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleMaps.vue")['default']
export const ScriptIntercom: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptIntercom.vue")['default']
export const ScriptLemonSqueezy: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLemonSqueezy.vue")['default']
export const ScriptLoadingIndicator: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLoadingIndicator.vue")['default']
export const ScriptStripePricingTable: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptStripePricingTable.vue")['default']
export const ScriptVimeoPlayer: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptVimeoPlayer.vue")['default']
export const ScriptYouTubePlayer: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptYouTubePlayer.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const MDC: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
export const MDCRenderer: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
export const MDCSlot: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
export const Icon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const SiteLink: typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
export const RobotMeta: typeof import("../node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
export const OgImage: typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImage")['default']
export const OgImageScreenshot: typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImageScreenshot")['default']
export const SchemaOrgDebug: typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
export const SchemaOrgArticle: typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
export const SchemaOrgBreadcrumb: typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
export const SchemaOrgComment: typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
export const SchemaOrgEvent: typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
export const SchemaOrgFoodEstablishment: typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
export const SchemaOrgHowTo: typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
export const SchemaOrgImage: typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
export const SchemaOrgJobPosting: typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
export const SchemaOrgLocalBusiness: typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
export const SchemaOrgOrganization: typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
export const SchemaOrgPerson: typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
export const SchemaOrgProduct: typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
export const SchemaOrgQuestion: typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
export const SchemaOrgRecipe: typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
export const SchemaOrgReview: typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
export const SchemaOrgVideo: typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
export const SchemaOrgWebPage: typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
export const SchemaOrgWebSite: typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
export const SchemaOrgMovie: typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
export const SchemaOrgCourse: typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
export const SchemaOrgItemList: typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
export const SchemaOrgBook: typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
export const SchemaOrgSoftwareApp: typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyFeatureExample: typeof import("../components/content/advertisements/FeatureExample.vue")['default']
export const LazySponsorExample: typeof import("../components/content/advertisements/SponsorExample.vue")['default']
export const LazyBlogGrid: typeof import("../components/content/blog/BlogGrid.vue")['default']
export const LazyDirectoryGrid: typeof import("../components/content/directory/DirectoryGrid.vue")['default']
export const LazySearch: typeof import("../components/content/directory/Search.vue")['default']
export const LazyLinkButton: typeof import("../components/content/general/LinkButton.vue")['default']
export const LazyNewsletterForm: typeof import("../components/content/general/NewsletterForm.vue")['default']
export const LazyNewsletterWithCTA: typeof import("../components/content/general/NewsletterWithCTA.vue")['default']
export const LazyTweet: typeof import("../components/content/general/Tweet.vue")['default']
export const LazyCenterHero: typeof import("../components/content/hero/CenterHero.vue")['default']
export const LazyImageHero: typeof import("../components/content/hero/ImageHero.vue")['default']
export const LazySimpleLeftHero: typeof import("../components/content/hero/SimpleLeftHero.vue")['default']
export const LazyTwoColumnHero: typeof import("../components/content/hero/TwoColumnHero.vue")['default']
export const LazyAbout: typeof import("../components/content/pages/About.vue")['default']
export const LazyBlogPost: typeof import("../components/content/pages/BlogPost.vue")['default']
export const LazyBlogs: typeof import("../components/content/pages/Blogs.vue")['default']
export const LazyChangelog: typeof import("../components/content/pages/Changelog.vue")['default']
export const LazyContact: typeof import("../components/content/pages/Contact.vue")['default']
export const LazyCustomer: typeof import("../components/content/pages/Customer.vue")['default']
export const LazyCustomers: typeof import("../components/content/pages/Customers.vue")['default']
export const LazyHelp: typeof import("../components/content/pages/Help.vue")['default']
export const LazyHome: typeof import("../components/content/pages/Home.vue")['default']
export const LazyIntegrations: typeof import("../components/content/pages/Integrations.vue")['default']
export const LazyIntegrationsSingle: typeof import("../components/content/pages/IntegrationsSingle.vue")['default']
export const LazyPricing: typeof import("../components/content/pages/Pricing.vue")['default']
export const LazyResetPassword: typeof import("../components/content/pages/ResetPassword.vue")['default']
export const LazySignIn: typeof import("../components/content/pages/SignIn.vue")['default']
export const LazySignUp: typeof import("../components/content/pages/SignUp.vue")['default']
export const LazyBlogList: typeof import("../components/content/partials/BlogList.vue")['default']
export const LazyBlogSingle: typeof import("../components/content/partials/BlogSingle.vue")['default']
export const LazyClients: typeof import("../components/content/partials/Clients.vue")['default']
export const LazyCta: typeof import("../components/content/partials/Cta.vue")['default']
export const LazyCta02: typeof import("../components/content/partials/Cta02.vue")['default']
export const LazyCta03: typeof import("../components/content/partials/Cta03.vue")['default']
export const LazyCta04: typeof import("../components/content/partials/Cta04.vue")['default']
export const LazyCta05: typeof import("../components/content/partials/Cta05.vue")['default']
export const LazyCustomersList: typeof import("../components/content/partials/CustomersList.vue")['default']
export const LazyCustomersRelated: typeof import("../components/content/partials/CustomersRelated.vue")['default']
export const LazyFaqs: typeof import("../components/content/partials/Faqs.vue")['default']
export const LazyFeatures: typeof import("../components/content/partials/Features.vue")['default']
export const LazyFeatures02: typeof import("../components/content/partials/Features02.vue")['default']
export const LazyFeatures03: typeof import("../components/content/partials/Features03.vue")['default']
export const LazyFeatures04: typeof import("../components/content/partials/Features04.vue")['default']
export const LazyFeatures05: typeof import("../components/content/partials/Features05.vue")['default']
export const LazyFooter: typeof import("../components/content/partials/Footer.vue")['default']
export const LazyHeader: typeof import("../components/content/partials/Header.vue")['default']
export const LazyHero: typeof import("../components/content/partials/Hero.vue")['default']
export const LazyHeroAbout: typeof import("../components/content/partials/HeroAbout.vue")['default']
export const LazyHighlighter: typeof import("../components/content/partials/Highlighter.vue")['default']
export const LazyHighlighterItem: typeof import("../components/content/partials/HighlighterItem.vue")['default']
export const LazyHighlighterItem02: typeof import("../components/content/partials/HighlighterItem02.vue")['default']
export const LazyIntegrationCard: typeof import("../components/content/partials/IntegrationCard.vue")['default']
export const LazyIntegrationsCarousel: typeof import("../components/content/partials/IntegrationsCarousel.vue")['default']
export const LazyIntegrationsHero: typeof import("../components/content/partials/IntegrationsHero.vue")['default']
export const LazyIntegrationsList: typeof import("../components/content/partials/IntegrationsList.vue")['default']
export const LazyPageIllustration: typeof import("../components/content/partials/PageIllustration.vue")['default']
export const LazyParticles: typeof import("../components/content/partials/Particles.vue")['default']
export const LazyPricingHero: typeof import("../components/content/partials/PricingHero.vue")['default']
export const LazyPricingHome: typeof import("../components/content/partials/PricingHome.vue")['default']
export const LazyPricingTable: typeof import("../components/content/partials/PricingTable.vue")['default']
export const LazyRecruitment: typeof import("../components/content/partials/Recruitment.vue")['default']
export const LazyStory: typeof import("../components/content/partials/Story.vue")['default']
export const LazyTeam: typeof import("../components/content/partials/Team.vue")['default']
export const LazyTestimonials: typeof import("../components/content/partials/Testimonials.vue")['default']
export const LazyTestimonials02: typeof import("../components/content/partials/Testimonials02.vue")['default']
export const LazyTestimonialsCarousel: typeof import("../components/content/partials/TestimonialsCarousel.vue")['default']
export const LazyProseA: typeof import("../components/content/prose/ProseA.vue")['default']
export const LazyTallyForm: typeof import("../components/content/submit/TallyForm.vue")['default']
export const LazyMousePosition: typeof import("../components/content/utils/MousePosition")['default']
export const LazyAppFooter: typeof import("../components/app/Footer.vue")['default']
export const LazyAppLayout: typeof import("../components/app/Layout.vue")['default']
export const LazyAppLogo: typeof import("../components/app/Logo.vue")['default']
export const LazyAppNavbar: typeof import("../components/app/Navbar.vue")['default']
export const LazyAppHeaderBanner: typeof import("../components/app/header/Banner.vue")['default']
export const LazyAppHeaderColorSelector: typeof import("../components/app/header/ColorSelector.vue")['default']
export const LazyAppHeaderDot: typeof import("../components/app/header/Dot.vue")['default']
export const LazyDirectoryEmptyQueryIndicator: typeof import("../components/directory/EmptyQueryIndicator.vue")['default']
export const LazyDirectoryFeaturedRecommendation: typeof import("../components/directory/Featured/Recommendation.vue")['default']
export const LazyDirectoryFeaturedTag: typeof import("../components/directory/Featured/Tag.vue")['default']
export const LazyDirectoryItem: typeof import("../components/directory/Item.vue")['default']
export const LazyDirectoryPureGrid: typeof import("../components/directory/PureGrid.vue")['default']
export const LazyDirectorySubmitBox: typeof import("../components/directory/SubmitBox.vue")['default']
export const LazyDocumentEmpty: typeof import("../components/document/Empty.vue")['default']
export const LazyDocumentNotFound: typeof import("../components/document/NotFound.vue")['default']
export const LazyDocumentProse: typeof import("../components/document/Prose.vue")['default']
export const LazyUiButton: typeof import("../components/ui/Button.vue")['default']
export const LazyUiCard: typeof import("../components/ui/Card.vue")['default']
export const LazyUiShadowCard: typeof import("../components/ui/ShadowCard.vue")['default']
export const LazyUiTag: typeof import("../components/ui/Tag.vue")['default']
export const LazyUiTagGrid: typeof import("../components/ui/tag/Grid.vue")['default']
export const LazyUiTagSelect: typeof import("../components/ui/tag/Select.vue")['default']
export const LazyContentDoc: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']
export const LazyContentList: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']
export const LazyContentNavigation: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']
export const LazyContentQuery: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']
export const LazyContentRenderer: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
export const LazyContentRendererMarkdown: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']
export const LazyContentSlot: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']
export const LazyDocumentDrivenEmpty: typeof import("../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue")['default']
export const LazyDocumentDrivenNotFound: typeof import("../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue")['default']
export const LazyMarkdown: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']
export const LazyProseCode: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue")['default']
export const LazyProseCodeInline: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default']
export const LazyProsePre: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue")['default']
export const LazyProseBlockquote: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
export const LazyProseEm: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
export const LazyProseH1: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
export const LazyProseH2: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
export const LazyProseH3: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
export const LazyProseH4: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
export const LazyProseH5: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
export const LazyProseH6: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
export const LazyProseHr: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
export const LazyProseImg: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
export const LazyProseLi: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
export const LazyProseOl: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
export const LazyProseP: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
export const LazyProseScript: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
export const LazyProseStrong: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
export const LazyProseTable: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
export const LazyProseTbody: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
export const LazyProseTd: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
export const LazyProseTh: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
export const LazyProseThead: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
export const LazyProseTr: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
export const LazyProseUl: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
export const LazyContentPreviewMode: typeof import("../node_modules/@nuxthq/studio/dist/runtime/components/ContentPreviewMode.vue")['default']
export const LazyScriptCarbonAds: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCarbonAds.vue")['default']
export const LazyScriptCrisp: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCrisp.vue")['default']
export const LazyScriptGoogleAdsense: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleAdsense.vue")['default']
export const LazyScriptGoogleMaps: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleMaps.vue")['default']
export const LazyScriptIntercom: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptIntercom.vue")['default']
export const LazyScriptLemonSqueezy: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLemonSqueezy.vue")['default']
export const LazyScriptLoadingIndicator: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLoadingIndicator.vue")['default']
export const LazyScriptStripePricingTable: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptStripePricingTable.vue")['default']
export const LazyScriptVimeoPlayer: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptVimeoPlayer.vue")['default']
export const LazyScriptYouTubePlayer: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptYouTubePlayer.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const LazyMDC: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
export const LazyMDCRenderer: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
export const LazyMDCSlot: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
export const LazyIcon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const LazyColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazySiteLink: typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
export const LazyRobotMeta: typeof import("../node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
export const LazyOgImage: typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImage")['default']
export const LazyOgImageScreenshot: typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImageScreenshot")['default']
export const LazySchemaOrgDebug: typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
export const LazySchemaOrgArticle: typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
export const LazySchemaOrgBreadcrumb: typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
export const LazySchemaOrgComment: typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
export const LazySchemaOrgEvent: typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
export const LazySchemaOrgFoodEstablishment: typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
export const LazySchemaOrgHowTo: typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
export const LazySchemaOrgImage: typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
export const LazySchemaOrgJobPosting: typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
export const LazySchemaOrgLocalBusiness: typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
export const LazySchemaOrgOrganization: typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
export const LazySchemaOrgPerson: typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
export const LazySchemaOrgProduct: typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
export const LazySchemaOrgQuestion: typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
export const LazySchemaOrgRecipe: typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
export const LazySchemaOrgReview: typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
export const LazySchemaOrgVideo: typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
export const LazySchemaOrgWebPage: typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
export const LazySchemaOrgWebSite: typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
export const LazySchemaOrgMovie: typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
export const LazySchemaOrgCourse: typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
export const LazySchemaOrgItemList: typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
export const LazySchemaOrgBook: typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
export const LazySchemaOrgSoftwareApp: typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
