// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/13/2024, 12:06:15 AM
const configMerger = require("/home/suneel/projects/mindtris/mindtris/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/home/suneel/projects/mindtris/mindtris/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/suneel/projects/mindtris/mindtris/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/suneel/projects/mindtris/mindtris/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/suneel/projects/mindtris/mindtris/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/suneel/projects/mindtris/mindtris/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/suneel/projects/mindtris/mindtris/plugins/**/*.{js,ts,mjs}","/home/suneel/projects/mindtris/mindtris/composables/**/*.{js,ts,mjs}","/home/suneel/projects/mindtris/mindtris/utils/**/*.{js,ts,mjs}","/home/suneel/projects/mindtris/mindtris/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/suneel/projects/mindtris/mindtris/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/suneel/projects/mindtris/mindtris/app.config.{js,ts,mjs}"] } }));

module.exports = (() => {const cfg=config;cfg["content"]["files"]["11"] = "/home/suneel/projects/mindtris/mindtris/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
